coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  backend:
    paths:
      - "backend/istudyspot-backend/"
    carryforward: true
  android:
    paths:
      - "frontend/Android/"
    carryforward: true
  miniprogram:
    paths:
      - "miniprogram/mp-user/"
    carryforward: true

ignore:
  - "**/config/"
  - "**/dto/"
  - "**/entity/"
  - "**/mapper/"
  - "**/controller/"
  - "**/IstudyspotBackendApplication.java"

parsers:
  java:
    branch_detection:
      conditional: true
      loop: true
      method: false
      exception: true
