CREATE TABLE IF NOT EXISTS `seat_layout_item` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '布局元素ID',
    `room_id` BIGINT NOT NULL COMMENT '自习室ID',
    `area_id` BIGINT DEFAULT NULL COMMENT '区域ID',
    `seat_id` BIGINT DEFAULT NULL COMMENT '关联座位ID',
    `item_type` VARCHAR(32) NOT NULL COMMENT '元素类型 seat/aisle/door/window/pillar/front_desk/plant/wall/zone_label',
    `item_key` VARCHAR(64) DEFAULT NULL COMMENT '布局元素唯一键',
    `label` VARCHAR(100) DEFAULT NULL COMMENT '元素标签',
    `row_num` INT NOT NULL COMMENT '起始行',
    `col_num` INT NOT NULL COMMENT '起始列',
    `width_units` INT NOT NULL DEFAULT 1 COMMENT '横向占位',
    `height_units` INT NOT NULL DEFAULT 1 COMMENT '纵向占位',
    `rotation` INT NOT NULL DEFAULT 0 COMMENT '旋转角度',
    `z_index` INT NOT NULL DEFAULT 0 COMMENT '渲染层级',
    `metadata` TEXT DEFAULT NULL COMMENT '额外信息(JSON)',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (`room_id`) REFERENCES `study_room` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`area_id`) REFERENCES `area` (`id`) ON DELETE SET NULL,
    FOREIGN KEY (`seat_id`) REFERENCES `seat` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uk_layout_item_key` (`room_id`, `item_key`),
    UNIQUE KEY `uk_layout_seat` (`seat_id`),
    INDEX `idx_layout_room` (`room_id`, `row_num`, `col_num`),
    INDEX `idx_layout_type` (`item_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='座位布局元素表';
