SET @room2 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 静心自习室（中关村店）' LIMIT 1);
SET @room3 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 24h自习舱（望京店）' LIMIT 1);
SET @room4 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 安静学习舱（学院路店）' LIMIT 1);
SET @room5 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 城市自习室（西二旗店）' LIMIT 1);
SET @room6 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 深夜学习站（国贸店）' LIMIT 1);
SET @room7 := (SELECT `id` FROM `study_room` WHERE `name` = 'iStudySpot 专注自习馆（望京北店）' LIMIT 1);

DELETE FROM `seat_layout_item`
WHERE `room_id` IN (@room2, @room3, @room4, @room5, @room6, @room7)
  AND `item_type` <> 'seat';

INSERT INTO `seat_layout_item` (`room_id`, `area_id`, `item_type`, `item_key`, `label`, `row_num`, `col_num`, `width_units`, `height_units`, `rotation`, `z_index`, `metadata`) VALUES
    (@room2, NULL, 'front_desk', 'room2-front-desk', '前台', 1, 1, 2, 1, 0, 10, '{"color":"wood"}'),
    (@room2, NULL, 'aisle', 'room2-aisle-top', '通道', 1, 4, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room2, NULL, 'door', 'room2-door', '入口', 1, 7, 1, 1, 0, 10, '{"side":"north"}'),
    (@room2, NULL, 'plant', 'room2-plant-entrance', '迎宾绿植', 1, 8, 1, 1, 0, 8, '{"kind":"bamboo"}'),
    (@room2, NULL, 'window', 'room2-window-west', '落地窗', 2, 1, 4, 1, 0, 5, '{"side":"west"}'),
    (@room2, NULL, 'zone_label', 'room2-zone-window', '窗景区', 2, 8, 2, 1, 0, 9, '{"zone":"window"}'),
    (@room2, NULL, 'table', 'room2-table-a', '共享长桌A', 3, 8, 4, 2, 0, 4, '{"shape":"long"}'),
    (@room2, NULL, 'aisle', 'room2-main-aisle', '主走道', 5, 1, 6, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room2, NULL, 'zone_label', 'room2-zone-lounge', '休息区', 6, 1, 2, 1, 0, 9, '{"zone":"lounge"}'),
    (@room2, NULL, 'lounge_counter', 'room2-lounge', '休息角', 6, 3, 3, 1, 0, 4, '{"shape":"lounge"}'),
    (@room2, NULL, 'table', 'room2-table-c', '标准长桌C', 7, 1, 5, 1, 0, 4, '{"shape":"long"}'),
    (@room2, NULL, 'zone_label', 'room2-zone-quiet', '静音区', 7, 11, 2, 1, 0, 9, '{"zone":"quiet"}'),
    (@room2, NULL, 'table', 'room2-table-d', '标准长桌D', 8, 1, 4, 1, 0, 4, '{"shape":"standard"}'),
    (@room2, NULL, 'plant', 'room2-plant-1', '绿植', 8, 12, 1, 1, 0, 8, '{"kind":"ficus"}'),
    (@room2, NULL, 'booth', 'room2-booth-a', '独立隔间A', 9, 1, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room2, NULL, 'zone_label', 'room2-zone-booth', '隔间区', 9, 4, 2, 1, 0, 9, '{"zone":"booth"}'),

    (@room3, NULL, 'front_desk', 'room3-front-desk', '夜间值守台', 1, 1, 2, 1, 0, 10, '{"staffed":"night"}'),
    (@room3, NULL, 'aisle', 'room3-aisle-top', '通道', 1, 3, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room3, NULL, 'door', 'room3-door', '入口', 1, 6, 1, 1, 0, 10, '{"side":"north"}'),
    (@room3, NULL, 'plant', 'room3-plant-entrance', '夜间绿植', 1, 7, 1, 1, 0, 8, '{"kind":"cactus"}'),
    (@room3, NULL, 'window', 'room3-window-east', '街景窗', 2, 9, 2, 2, 0, 5, '{"side":"east"}'),
    (@room3, NULL, 'zone_label', 'room3-zone-focus', '深夜专注区', 2, 1, 3, 1, 0, 9, '{"zone":"focus"}'),
    (@room3, NULL, 'zone_label', 'room3-zone-booth', '隔间区', 2, 5, 2, 1, 0, 9, '{"zone":"booth"}'),
    (@room3, NULL, 'table', 'room3-table-a', '深夜长桌A', 3, 7, 3, 2, 0, 4, '{"shape":"long"}'),
    (@room3, NULL, 'aisle', 'room3-main-aisle', '夜间主通道', 6, 1, 6, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room3, NULL, 'booth', 'room3-booth-a', '冲刺隔间A', 7, 1, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room3, NULL, 'booth', 'room3-booth-b', '冲刺隔间B', 7, 3, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room3, NULL, 'table', 'room3-table-c', '标准桌C', 7, 9, 2, 2, 0, 4, '{"shape":"standard"}'),
    (@room3, NULL, 'zone_label', 'room3-zone-standard', '标准区', 8, 1, 2, 1, 0, 9, '{"zone":"standard"}'),
    (@room3, NULL, 'lounge_counter', 'room3-lounge', '充电沙发位', 8, 3, 3, 1, 0, 4, '{"shape":"lounge"}'),
    (@room3, NULL, 'plant', 'room3-plant-1', '补给台', 8, 6, 1, 1, 0, 8, '{"kind":"supply"}'),
    (@room3, NULL, 'zone_label', 'room3-zone-lounge', '休息充电区', 9, 1, 3, 1, 0, 9, '{"zone":"lounge"}'),
    (@room3, NULL, 'table', 'room3-table-pc', '电脑桌', 10, 1, 4, 1, 0, 4, '{"shape":"pc"}'),

    (@room4, NULL, 'front_desk', 'room4-front-desk', '咨询台', 1, 1, 2, 1, 0, 10, '{"color":"walnut"}'),
    (@room4, NULL, 'aisle', 'room4-aisle-top', '通道', 1, 3, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room4, NULL, 'door', 'room4-door', '入口', 1, 6, 1, 1, 0, 10, '{"side":"north"}'),
    (@room4, NULL, 'plant', 'room4-plant-entrance', '入口绿植', 1, 7, 1, 1, 0, 8, '{"kind":"fern"}'),
    (@room4, NULL, 'window', 'room4-window', '采光窗', 2, 1, 4, 1, 0, 5, '{"side":"west"}'),
    (@room4, NULL, 'zone_label', 'room4-zone-focus', '沉浸区', 2, 6, 2, 1, 0, 9, '{"zone":"focus"}'),
    (@room4, NULL, 'table', 'room4-table-a', '双人书桌A', 3, 3, 2, 2, 0, 4, '{"shape":"double"}'),
    (@room4, NULL, 'table', 'room4-table-b', '双人书桌B', 3, 6, 2, 2, 0, 4, '{"shape":"double"}'),
    (@room4, NULL, 'aisle', 'room4-main-aisle', '中心走道', 5, 3, 2, 2, 0, 1, '{"orientation":"block"}'),
    (@room4, NULL, 'zone_label', 'room4-zone-vip2', 'VIP沙发区', 5, 6, 2, 1, 0, 9, '{"zone":"vip"}'),
    (@room4, NULL, 'pillar', 'room4-pillar-1', '立柱', 6, 5, 1, 1, 0, 8, '{"shape":"square"}'),
    (@room4, NULL, 'booth', 'room4-booth-a', '冲刺隔间A', 8, 6, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room4, NULL, 'booth', 'room4-booth-b', '冲刺隔间B', 8, 3, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room4, NULL, 'zone_label', 'room4-zone-booth', '隔间区', 8, 1, 2, 1, 0, 9, '{"zone":"booth"}'),
    (@room4, NULL, 'plant', 'room4-plant-2', '静音绿植', 9, 5, 1, 1, 0, 8, '{"kind":"bamboo"}'),
    (@room4, NULL, 'zone_label', 'room4-zone-quiet', '静音区', 10, 6, 2, 1, 0, 9, '{"zone":"quiet"}'),

    (@room5, NULL, 'front_desk', 'room5-front-desk', '服务台', 1, 1, 2, 1, 0, 10, '{"color":"light"}'),
    (@room5, NULL, 'aisle', 'room5-aisle-top', '通道', 1, 3, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room5, NULL, 'door', 'room5-door', '入口', 1, 6, 1, 1, 0, 10, '{"side":"north"}'),
    (@room5, NULL, 'plant', 'room5-plant-entrance', '入口装饰', 1, 7, 1, 1, 0, 8, '{"kind":"orchid"}'),
    (@room5, NULL, 'window', 'room5-window', '通长窗', 2, 1, 4, 1, 0, 5, '{"side":"south"}'),
    (@room5, NULL, 'zone_label', 'room5-zone-standard', '标准区', 2, 6, 2, 1, 0, 9, '{"zone":"standard"}'),
    (@room5, NULL, 'table', 'room5-table-a', '标准长桌A', 3, 3, 2, 2, 0, 4, '{"shape":"long"}'),
    (@room5, NULL, 'table', 'room5-table-b', '标准长桌B', 3, 6, 2, 2, 0, 4, '{"shape":"long"}'),
    (@room5, NULL, 'aisle', 'room5-main-aisle', '中庭走廊', 5, 3, 2, 2, 0, 1, '{"orientation":"block"}'),
    (@room5, NULL, 'zone_label', 'room5-zone-vip2', 'VIP沙发区', 5, 6, 2, 1, 0, 9, '{"zone":"vip"}'),
    (@room5, NULL, 'pillar', 'room5-pillar-1', '立柱', 6, 5, 1, 1, 0, 8, '{"shape":"round"}'),
    (@room5, NULL, 'zone_label', 'room5-zone-discuss', '讨论区', 8, 6, 2, 1, 0, 9, '{"zone":"discussion"}'),
    (@room5, NULL, 'lounge_counter', 'room5-lounge', '讨论沙发', 8, 3, 2, 1, 0, 4, '{"shape":"lounge"}'),
    (@room5, NULL, 'plant', 'room5-plant-1', '绿植角', 8, 5, 1, 1, 0, 8, '{"kind":"monstera"}'),
    (@room5, NULL, 'window', 'room5-window-bottom', '侧窗', 9, 6, 2, 1, 0, 5, '{"side":"south"}'),
    (@room5, NULL, 'table', 'room5-table-c', '电脑桌C', 10, 6, 2, 1, 0, 4, '{"shape":"pc"}'),

    (@room6, NULL, 'front_desk', 'room6-front-desk', '夜猫补给台', 1, 1, 2, 1, 0, 10, '{"open":"24h"}'),
    (@room6, NULL, 'aisle', 'room6-aisle-top', '通道', 1, 3, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room6, NULL, 'door', 'room6-door', '入口', 1, 6, 1, 1, 0, 10, '{"side":"north"}'),
    (@room6, NULL, 'plant', 'room6-plant-entrance', '夜间绿植', 1, 7, 1, 1, 0, 8, '{"kind":"aloe"}'),
    (@room6, NULL, 'window', 'room6-window', '夜景窗', 2, 6, 2, 1, 0, 5, '{"side":"east"}'),
    (@room6, NULL, 'zone_label', 'room6-zone-focus', '深夜专注区', 2, 1, 3, 1, 0, 9, '{"zone":"focus"}'),
    (@room6, NULL, 'table', 'room6-table-a', '夜读长桌A', 3, 3, 2, 2, 0, 4, '{"shape":"long"}'),
    (@room6, NULL, 'table', 'room6-table-b', '夜读长桌B', 3, 6, 2, 2, 0, 4, '{"shape":"long"}'),
    (@room6, NULL, 'aisle', 'room6-main-aisle', '补给通道', 5, 3, 2, 2, 0, 1, '{"orientation":"block"}'),
    (@room6, NULL, 'booth', 'room6-booth-a', '独立隔间A', 5, 8, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room6, NULL, 'zone_label', 'room6-zone-standard', '标准区', 7, 1, 2, 1, 0, 9, '{"zone":"standard"}'),
    (@room6, NULL, 'table', 'room6-table-c', '标准桌C', 7, 6, 2, 1, 0, 4, '{"shape":"standard"}'),
    (@room6, NULL, 'lounge_counter', 'room6-lounge', '休息沙发', 8, 3, 2, 1, 0, 4, '{"shape":"lounge"}'),
    (@room6, NULL, 'plant', 'room6-plant-1', '补给绿植', 8, 5, 1, 1, 0, 8, '{"kind":"snake_plant"}'),
    (@room6, NULL, 'zone_label', 'room6-zone-rest', '休息区', 8, 6, 2, 1, 0, 9, '{"zone":"rest"}'),
    (@room6, NULL, 'booth', 'room6-booth-c', 'VIP隔间', 9, 3, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room6, NULL, 'table', 'room6-table-pc', '电脑桌', 10, 6, 2, 1, 0, 4, '{"shape":"pc"}'),

    (@room7, NULL, 'front_desk', 'room7-front-desk', '签到台', 1, 1, 2, 1, 0, 10, '{"color":"dark"}'),
    (@room7, NULL, 'aisle', 'room7-aisle-top', '通道', 1, 3, 3, 1, 0, 1, '{"orientation":"horizontal"}'),
    (@room7, NULL, 'door', 'room7-door', '入口', 1, 6, 1, 1, 0, 10, '{"side":"north"}'),
    (@room7, NULL, 'plant', 'room7-plant-entrance', '迎客松', 1, 7, 1, 1, 0, 8, '{"kind":"pine"}'),
    (@room7, NULL, 'window', 'room7-window', '北侧采光', 2, 1, 4, 1, 0, 5, '{"side":"north"}'),
    (@room7, NULL, 'zone_label', 'room7-zone-silent', '静音专注区', 2, 6, 2, 1, 0, 9, '{"zone":"silent"}'),
    (@room7, NULL, 'table', 'room7-table-a', '静音长桌A', 3, 3, 2, 2, 0, 4, '{"shape":"silent"}'),
    (@room7, NULL, 'table', 'room7-table-b', '静音长桌B', 3, 6, 2, 2, 0, 4, '{"shape":"silent"}'),
    (@room7, NULL, 'aisle', 'room7-main-aisle', '主通道', 5, 3, 2, 2, 0, 1, '{"orientation":"block"}'),
    (@room7, NULL, 'zone_label', 'room7-zone-vip', '靠窗VIP', 5, 6, 2, 1, 0, 9, '{"zone":"vip"}'),
    (@room7, NULL, 'pillar', 'room7-pillar-1', '立柱', 6, 5, 1, 1, 0, 8, '{"shape":"square"}'),
    (@room7, NULL, 'zone_label', 'room7-zone-sun', '阳光学习区', 7, 6, 2, 1, 0, 9, '{"zone":"sunshine"}'),
    (@room7, NULL, 'plant', 'room7-plant-1', '静音绿植', 8, 5, 1, 1, 0, 8, '{"kind":"fern"}'),
    (@room7, NULL, 'table', 'room7-table-group', '小组桌', 8, 3, 2, 1, 0, 4, '{"shape":"group"}'),
    (@room7, NULL, 'lounge_counter', 'room7-lounge', '讨论沙发', 8, 6, 2, 1, 0, 4, '{"shape":"lounge"}'),
    (@room7, NULL, 'booth', 'room7-booth-a', '讨论隔间', 9, 3, 2, 1, 0, 4, '{"shape":"booth"}'),
    (@room7, NULL, 'zone_label', 'room7-zone-group', '小组讨论区', 10, 6, 2, 1, 0, 9, '{"zone":"group"}');
