CREATE TABLE IF NOT EXISTS `order` (
                                       `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID',
                                       `order_no` VARCHAR(32) UNIQUE NOT NULL COMMENT '订单号',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `seat_id` BIGINT NOT NULL COMMENT '座位ID',
    `seat_number` VARCHAR(20) COMMENT '座位编号（冗余）',
    `room_id` BIGINT NOT NULL COMMENT '自习室ID',
    `room_name` VARCHAR(100) COMMENT '自习室名称（冗余）',
    `plan_start_time` DATETIME NOT NULL COMMENT '计划开始时间',
    `plan_end_time` DATETIME NOT NULL COMMENT '计划结束时间',
    `actual_start_time` DATETIME COMMENT '实际签到时间',
    `actual_end_time` DATETIME COMMENT '实际签退时间',
    `total_hours` DECIMAL(5,1) COMMENT '总时长（小时）',
    `unit_price` DECIMAL(10,2) COMMENT '平均单价',
    `total_amount` DECIMAL(10,2) NOT NULL COMMENT '总金额',
    `pay_amount` DECIMAL(10,2) COMMENT '实付金额',
    `deposit` DECIMAL(10,2) DEFAULT 0 COMMENT '押金',
    `status` TINYINT NOT NULL COMMENT '状态：1-待支付 2-已支付待使用 3-使用中 4-已完成 5-已取消 6-退款中 7-已退款',
    `pay_type` TINYINT COMMENT '支付方式：1-余额 2-微信 3-支付宝',
    `pay_time` DATETIME COMMENT '支付时间',
    `cancel_reason` VARCHAR(255) COMMENT '取消原因',
    `cancel_time` DATETIME COMMENT '取消时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
    FOREIGN KEY (`seat_id`) REFERENCES `seat` (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_seat_id` (`seat_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_create_time` (`create_time`),
    INDEX `idx_plan_time` (`plan_start_time`, `plan_end_time`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';